declare class TiandituImageryProvider {
    _mapStyle: string;
    _url: string;
    _token: string;
    _layer: string;
    _style: string;
    _tileMatrixSetID: string;
    _tileMatrixLabels: string;
    _format: string;
    _epsgCode: string;
    _tilingScheme: any;
    _tileWidth: number;
    _tileHeight: number;
    _minimumLevel: number;
    _maximumLevel: number;
    _rectangle: any;
    _readyPromise: any;
    _errorEvent: any;
    _credit: any;
    _subdomains: [];
    _tileDiscardPolicy: any;
    constructor(options: any);
    requestImage(x: any, y: any, level: any): Promise<HTMLImageElement | HTMLCanvasElement>;
    pickFeatures(x: any, y: any, level: any, longitude: any, latitude: any): any;
    get url(): string;
    get mapStyle(): string;
    get tileWidth(): number;
    get tileHeight(): number;
    get maximumLevel(): number;
    get minimumLevel(): number;
    get tilingScheme(): any;
    get rectangle(): any;
    get errorEvent(): any;
    get ready(): boolean;
    get readyPromise(): any;
    get credit(): any;
    get hasAlphaChannel(): boolean;
    get tileDiscardPolicy(): any;
}
export default TiandituImageryProvider;
