declare const TiandituMapsStyle: {
    IMG_W: string;
    IMG_C: string;
    CIA_W: string;
    CIA_C: string;
    VEC_W: string;
    VEC_C: string;
    TER_W: string;
    TER_C: string;
    CVA_W: string;
    CVA_C: string;
    CTA_W: string;
    CTA_C: string;
    EIA_W: string;
    EIA_C: string;
    EVA_W: string;
    EVA_C: string;
    IBO_C: string;
    IBO_W: string;
};
export default TiandituMapsStyle;
