declare class SuperMapImageryProvider {
    tablename: string;
    _indexedDBScheduler: any;
    _indexedDBSetting: {
        isOpen: boolean;
        clear: () => void;
    };
    isSci: boolean;
    isTileMap: boolean;
    layersID: string;
    _url: string;
    _resource: any;
    _transparent: boolean;
    _name: string;
    _urlTemplate: string;
    _errorEvent: any;
    _fileExtension: string;
    _tileWidth: number;
    _tileHeight: number;
    _minimumLevel: number;
    _maximumLevel: number;
    _rectangle: any;
    _tilingScheme: any;
    _tileDiscardPolicy: any;
    _fRatio: any;
    _scales: any[];
    _coordUnit: string;
    _credit: any;
    _ready: boolean;
    _readyPromise: any;
    _options: any;
    constructor(options: any);
    get url(): string;
    get name(): string;
    set name(val: string);
    get tileWidth(): number;
    get tileHeight(): number;
    get maximumLevel(): number;
    get minimumLevel(): number;
    get tilingScheme(): any;
    get rectangle(): any;
    get errorEvent(): any;
    get ready(): boolean;
    get credit(): any;
    get hasAlphaChannel(): boolean;
    get readyPromise(): any;
    get ratio(): any;
    set ratio(val: any);
    get tileDiscardPolicy(): any;
    getTileCredits(x: any, y: any, level: any): any;
    requestImage(x: any, y: any, level: any, request: any): any;
    pickFeatures(x: any, y: any, level: any, longitude: any, latitude: any): any;
}
export default SuperMapImageryProvider;
