import installer from './defaults';
export * from 'vue-cesium/es/components';
export * from 'vue-cesium/es/directives';
export * from 'vue-cesium/es/composables';
export * from 'vue-cesium/es/shared';
export * from 'vue-cesium/es/utils/emits';
export { default as makeInstaller } from './make-installer';
export declare const install: (app: import("vue").App<any>, opts: import("./utils/config").ConfigProviderContext) => void;
export declare const version: string;
export default installer;
