import type { VcGeometryPolylineProps } from 'vue-cesium/es/components/geometries';
import type { VcBillboardProps, VcLabelProps, VcPointProps } from 'vue-cesium/es/components/primitive-collections';
import type { VcPrimitiveGroundPolylineProps, VcPrimitiveProps } from 'vue-cesium/es/components/primitives';
import type { VcDrawingOpts } from 'vue-cesium/es/utils/drawing-types';
import type { VcActionTooltipProps, VcBtnTooltipProps } from 'vue-cesium/es/utils/types';
declare const actionOptions: VcActionTooltipProps;
declare const polylinePrimitiveOptsDefault: VcPrimitiveProps & VcPrimitiveGroundPolylineProps;
declare const pointOptsDefault: VcPointProps;
declare const billboardOptsDefault: VcBillboardProps;
declare const polylineOptsDefault: VcGeometryPolylineProps;
declare const labelOptsDefault: VcLabelProps;
declare const editorOptsDefault: VcBtnTooltipProps;
declare const pointDrawingDefault: VcDrawingOpts;
declare const segmentDrawingDefault: VcDrawingOpts;
declare const polylineDrawingDefault: VcDrawingOpts;
declare const polygonDrawingDefault: VcDrawingOpts;
declare const rectangleDrawingDefault: VcDrawingOpts;
declare const circleDrawingDefault: VcDrawingOpts;
declare const regularDrawingDefault: VcDrawingOpts;
declare const clearActionDefault: VcActionTooltipProps;
declare const regularDrawingActionDefault: VcActionTooltipProps;
declare const circleDrawingActionDefault: VcActionTooltipProps;
export { actionOptions, clearActionDefault, editorOptsDefault, pointOptsDefault, billboardOptsDefault, labelOptsDefault, polylineOptsDefault, pointDrawingDefault, segmentDrawingDefault, polylineDrawingDefault, polygonDrawingDefault, rectangleDrawingDefault, circleDrawingDefault, circleDrawingActionDefault, regularDrawingDefault, regularDrawingActionDefault, polylinePrimitiveOptsDefault };
